# safelist
branches:
  only:
  - master
  - deploy

language: python
python:
  - 3.7
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install zappa

stages:
  - name: Dev
    if: branch = master

  - name: Prod
    if: branch = deploy

jobs:
  include:
    - stage: Dev
      script:
      - pytest
      - zappa update -s zappa_settings.json dev
    
    - stage: Prod
      script:
      - pytest
      - zappa update -s zappa_settings.json prod
